apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kompose.cmd: kompose convert -f app.yml
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose convert -f app.yml","kompose.version":"1.16.0 (0c01309)"},"creationTimestamp":null,"labels":{"io.kompose.service":"app"},"name":"app","namespace":"dev"},"spec":{"minReadySeconds":60,"replicas":1,"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"io.kompose.service":"app"}},"spec":{"containers":[{"env":[{"name":"EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE","value":"http://admin:${jhipster.registry.password}@jhipster-registry.dev.svc.cluster.local:8761/eureka"},{"name":"JHIPSTER_SLEEP","value":"30"},{"name":"MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED","value":"true"},{"name":"SPRING_CLOUD_CONFIG_URI","value":"http://admin:${jhipster.registry.password}@jhipster-registry.dev.svc.cluster.local:8761/config"},{"name":"SPRING_DATASOURCE_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"rds_endpoint","name":"rds-dev"}}},{"name":"SPRING_DATASOURCE_DB","valueFrom":{"secretKeyRef":{"key":"rds_db","name":"rds-dev"}}},{"name":"SPRING_DATASOURCE_URL","value":"jdbc:postgresql://${SPRING_DATASOURCE_ENDPOINT}:5432/${SPRING_DATASOURCE_DB}"},{"name":"SPRING_DATASOURCE_USERNAME","valueFrom":{"secretKeyRef":{"key":"rds_username","name":"rds-dev"}}},{"name":"SPRING_DATASOURCE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"rds_password","name":"rds-dev"}}},{"name":"SPRING_DATA_JEST_URI","valueFrom":{"secretKeyRef":{"key":"elastic_uri","name":"elastic-dev"}}},{"name":"SPRING_ELASTICSEARCH_REST_URIS","valueFrom":{"secretKeyRef":{"key":"elastic_uri","name":"elastic-dev"}}},{"name":"SPRING_PROFILES_ACTIVE","value":"prod,swagger"},{"name":"SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI","value":"http://a3b074eae096711eabbcf0aada69bbba-1199628500.us-east-1.elb.amazonaws.com/auth/realms/jhipster"},{"name":"SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID","value":"web_app"},{"name":"SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET","value":"web_app"},{"name":"DEFAULT_BUCKET","valueFrom":{"secretKeyRef":{"key":"bucket_name","name":"bucket-dev"}}},{"name":"DEFAULT_REGION","value":"us-east-1"},{"name":"ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"aws_access","name":"aws-keys"}}},{"name":"ACCESS_KEY_SECRET","valueFrom":{"secretKeyRef":{"key":"aws_secret","name":"aws-keys"}}},{"name":"KMS_KEY","valueFrom":{"secretKeyRef":{"key":"kms_key_id","name":"kms-key"}}}],"image":"octolabs/fedhipster-app","name":"app","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"750m","memory":"3Gi"},"requests":{"cpu":"500m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/tmp","name":"temp-dir"}]}],"restartPolicy":"Always","volumes":[{"emptyDir":{},"name":"temp-dir"}]}}},"status":{}}
    kubernetes.io/change-cause: kubectl deploy/app set image app=294545192489.dkr.ecr.us-east-1.amazonaws.com/app:dev-16
      --namespace=dev --record=true
  creationTimestamp: null
  generation: 1
  labels:
    io.kompose.service: app
    kube-monkey/enabled: enabled
    kube-monkey/identifier: app
    kube-monkey/mtbf: '1'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
  name: app
  selfLink: /apis/extensions/v1beta1/namespaces/dev/deployments/app
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
        kube-monkey/enabled: enabled
        kube-monkey/identifier: app
        kube-monkey/mtbf: '1'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.dev.svc.cluster.local:8761/eureka
        - name: JHIPSTER_SLEEP
          value: "30"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.dev.svc.cluster.local:8761/config
        - name: SPRING_DATASOURCE_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: rds_endpoint
              name: rds-dev
        - name: SPRING_DATASOURCE_DB
          valueFrom:
            secretKeyRef:
              key: rds_db
              name: rds-dev
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://${SPRING_DATASOURCE_ENDPOINT}:5432/${SPRING_DATASOURCE_DB}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: rds_username
              name: rds-dev
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rds_password
              name: rds-dev
        - name: SPRING_DATA_JEST_URI
          valueFrom:
            secretKeyRef:
              key: elastic_uri
              name: elastic-dev
        - name: SPRING_ELASTICSEARCH_REST_URIS
          valueFrom:
            secretKeyRef:
              key: elastic_uri
              name: elastic-dev
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
          value: http://a3b074eae096711eabbcf0aada69bbba-1199628500.us-east-1.elb.amazonaws.com/auth/realms/jhipster
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID
          value: web_app
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET
          value: web_app
        - name: DEFAULT_BUCKET
          valueFrom:
            secretKeyRef:
              key: bucket_name
              name: bucket-dev
        - name: DEFAULT_REGION
          value: us-east-1
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access
              name: aws-keys
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: aws_secret
              name: aws-keys
        - name: KMS_KEY
          valueFrom:
            secretKeyRef:
              key: kms_key_id
              name: kms-key
        image: 294545192489.dkr.ecr.us-east-1.amazonaws.com/app:dev-16
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 750m
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: temp-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: temp-dir
status: {}
