apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f app.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: app
  type: LoadBalancer  
status:
  loadBalancer: {}
