apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f app.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ports:
  - name: "9080"
    port: 80
    targetPort: 9080
  - name: "9443"
    port: 9443
    targetPort: 9443
  - name: "10990"
    port: 10990
    targetPort: 10990
  selector:
    io.kompose.service: keycloak
  type: LoadBalancer
status:
  loadBalancer: {}
