apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f app.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: micro
  name: micro
spec:
  ports:
  - name: "8085"
    port: 80
    targetPort: 8085
  selector:
    io.kompose.service: micro
  type: LoadBalancer  
status:
  loadBalancer: {}
